id: OpenStreetMapVecto
server:
  host: localhost
  port: 9000
center:
  lon: 6.5743
  lat: 46.5189
  zoom: 14
bounds:
  minLon: 5.8358
  minLat: 45.6591
  maxLon: 10.9794
  maxLat: 47.8700
  minZoom: 6
  maxZoom: 14 
layers:
  - config/aerialway/layer.yaml
  - config/power/layer.yaml
  - config/amenity/layer.yaml
  - config/boundary/layer.yaml
  - config/building/layer.yaml
  - config/highway/layer.yaml
  - config/natural/layer.yaml
  - config/leisure/layer.yaml
  - config/landuse/layer.yaml
  - config/points/layer.yaml
  - config/railway/layer.yaml
  - config/route/layer.yaml
  - config/waterway/layer.yaml
  - config/water/layer.yaml
stylesheets:
  - config/power/stylesheet.yaml
  - config/points/stylesheet.yaml
  - config/boundary/stylesheet.yaml
  - config/route/stylesheet.yaml
  - config/railway/stylesheet.yaml
  - config/highway/stylesheet.yaml
  - config/building/stylesheet.yaml
  - config/waterway/stylesheet.yaml
  - config/water/stylesheet.yaml
  - config/landuse/stylesheet-overlay.yaml
  - config/amenity/stylesheet-overlay.yaml
  - config/natural/stylesheet-overlay.yaml
  - config/aerialway/stylesheet.yaml
  - config/leisure/stylesheet.yaml
  - config/natural/stylesheet.yaml
  - config/landuse/stylesheet.yaml
  - config/amenity/stylesheet.yaml
  - config/background/stylesheet.yaml
