id: building
type: polygon
queries:
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE tags ? 'building'
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations_z${zoom} 
      WHERE tags ? 'building'