id: leisure
type: polygon
queries:
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE geometrytype(geom) LIKE '%POLYGON%'
        AND tags ? 'leisure'
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations_z${zoom}
      WHERE geometrytype(geom) LIKE '%POLYGON%'
        AND tags ? 'leisure'