id: amenity
styles:
  - id: amenity_education
    layer: amenity
    type: fill
    layout:
      visibility: visible
    filter: [
      any,
      [==, amenity, kindergarten],
      [==, amenity, school],
      [==, amenity, college],
      [==, amenity, university],
    ]
    paint:
      fill-color: rgb(255, 255, 228)
      fill-antialias: true
