id: highway
type: linestring
queries:
  - minZoom: 0
    maxZoom: 8
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE tags -> 'highway' IN (
       'motorway', 'motorway_link', 
       'trunk', 'trunk_link', 
       'primary', 'primary_link')
  - minZoom: 8
    maxZoom: 11
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE tags -> 'highway' IN (
       'motorway', 'motorway_link', 
       'trunk', 'trunk_link', 
       'primary', 'primary_link', 
       'secondary', 'secondary_link',
       'tertiary', 'tertiary_link')
  - minZoom: 11
    maxZoom: 13
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE tags -> 'highway' IN (
       'motorway', 'motorway_link', 
       'trunk', 'trunk_link', 
       'primary', 'primary_link', 
       'secondary', 'secondary_link', 
       'tertiary', 'tertiary_link',
       'unclassified', 
       'residential')
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom}
      WHERE tags ? 'highway'
  - minZoom: 13
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations_z${zoom}
      WHERE tags ? 'highway'