id: highway
styles:
  - id: highway_motorway
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, motorway],
      [==, highway, motorway_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(233, 144, 161)
  - id: highway_motorway_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, motorway],
      [==, highway, motorway_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 16]
        ]
      line-color: rgb(227, 82, 126)
  - id: highway_trunk
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, trunk],
      [==, highway, trunk_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(250, 193, 172)
  - id: highway_trunk_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, trunk],
      [==, highway, trunk_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 16]
        ]
      line-color: rgb(217, 111, 78)
  - id: highway_primary
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, primary],
      [==, highway, primary_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(253, 221, 179)
  - id: highway_primary_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, primary],
      [==, highway, primary_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 16]
        ]
      line-color: rgb(192, 147, 62)
  - id: highway_secondary
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, secondary],
      [==, highway, secondary_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(248, 250, 202)
  - id: highway_secondary_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, secondary],
      [==, highway, secondary_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(154, 166, 67)
  - id: highway_tertiary
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, tertiary],
      [==, highway, tertiary_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(254, 254, 254)
  - id: highway_tertiary_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, tertiary],
      [==, highway, tertiary_link]
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(190, 189, 188)
  - id: highway_unclassified
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, unclassified],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(254, 254, 254)
  - id: highway_unclassified_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, unclassified],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(211, 207, 206)
  - id: highway_residential
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, residential],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(254, 254, 254)
  - id: highway_residential_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, residential],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 12]
        ]
      line-color: rgb(211, 207, 206)
  - id: highway_living_street
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, living_street],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 4]
        ]
      line-color: rgb(237, 237, 237)
  - id: highway_living_street_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, living_street],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(207, 207, 207)
  - id: highway_service
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, service],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 4]
        ]
      line-color: rgb(254, 254, 254)
  - id: highway_service_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, service],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(213, 211, 211)
  - id: highway_road
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, road],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 4]
        ]
      line-color: rgb(221, 221, 221)
  - id: highway_road_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, road],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(201, 201, 200)
  - id: highway_pedestrian
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      all,
      ['!has', area],
      [==, highway, pedestrian],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 4]
        ]
      line-color: rgb(221, 221, 231)
  - id: highway_pedestrian_casing
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      all,
      ['!has', area],
      [==, highway, pedestrian],
    ]
    paint:
      line-width: 
        base: 1.2
        stops: [
          [4, 0],
          [20, 8]
        ]
      line-color: rgb(184, 183, 182)
  - id: highway_pedestrian_area
    layer: highway
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      ['has', area],
      [==, highway, pedestrian],
    ]
    paint:
      fill-color: rgb(221, 221, 231)
      fill-outline-color: rgb(183, 183, 186)
      fill-antialias: true

  - id: highway_track
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, track],
    ]
    paint:
      line-width: 1
      line-color: rgb(173, 132, 39)
      line-dasharray: [4, 2, 2, 2]
  - id: highway_bus_guideway
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, bus_guideway],
    ]
    paint:
      line-width: 4
      line-color: rgb(102, 102, 255)
      line-dasharray: [4, 2]
  - id: highway_raceway
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, raceway],
    ]
    paint:
      line-width: 4
      line-color: rgb(254, 192, 202)
  - id: highway_path
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      'all',
      ['!has', area],
      [
        any,
        [==, highway, footway],
        [==, highway, path],
        [==, highway, sidewalk],
        [==, highway, crossing],
        [==, highway, steps],
      ],
      ]
    paint:
      line-width: 1
      line-color: rgb(250, 132, 117)
      line-dasharray: [2, 2]
  - id: highway_path_area
    layer: highway
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      ['has', area],
      [
        any,
        [==, highway, footway],
        [==, highway, path],
        [==, highway, sidewalk],
        [==, highway, crossing],
        [==, highway, steps],
      ],
    ]
    paint:
      fill-color: rgb(221, 221, 231)
      fill-outline-color: rgb(168, 181, 171)
      fill-antialias: true
  - id: highway_bridleway
    layer: highway
    type: line
    layout:
      visibility: visible
      line-cap: round
      line-join: round
    filter: [
      any,
      [==, highway, bridleway],
    ]
    paint:
      line-width: 1
      line-color: rgb(68, 159, 66)
      line-dasharray: [2, 2]
