id: landuse
styles:
  - id: landuse_pedestrian
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, highway, pedestrian]
    ]
    paint:
      fill-color: rgb(221, 221, 233)
      fill-outline-color: rgb(184, 183, 182)
      fill-antialias: true
  - id: landuse_commercial
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, commercial]
    ]
    paint:
      fill-color: rgb(242, 216, 217)
      fill-antialias: true
  - id: landuse_construction
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, construction]
    ]
    paint:
      fill-color: rgb(199, 199, 180)
      fill-antialias: true
  - id: landuse_residential
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, residential]
    ]
    paint:
      fill-color: rgb(225, 225, 225)
      fill-antialias: true
  - id: landuse_retail
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, retail]
    ]
    paint:
      fill-color: rgb(254, 213, 208)
      fill-antialias: true
  - id: landuse_allotments
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, allotments]
    ]
    paint:
      fill-color: rgb(202, 224, 191)
      fill-antialias: true
  - id: landuse_farmland
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, farmland]
    ]
    paint:
      fill-color: rgb(237, 240, 214)
      fill-antialias: true
  - id: landuse_farmyard
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, farmyard]
    ]
    paint:
      fill-color: rgb(238, 213, 179)
      fill-antialias: true
  - id: landuse_meadow
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, meadow]
    ]
    paint:
      fill-color: rgb(205, 235, 176)
      fill-antialias: true
  - id: landuse_orchard
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, orchard]
    ]
    paint:
      fill-color: rgb(172, 225, 161)
      fill-antialias: true
  - id: landuse_vineyard
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, vineyard]
    ]
    paint:
      fill-color: rgb(172, 225, 161)
      fill-antialias: true
  - id: landuse_basin
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, basin]
    ]
    paint:
      fill-color: rgb(170, 211, 223)
      fill-antialias: true
  - id: landuse_brownfield
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, brownfield]
    ]
    paint:
      fill-color: rgb(182, 182, 144)
      fill-antialias: true
  - id: landuse_cemetery
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, cemetery],
    ]
    paint:
      fill-color: rgb(170, 203, 175)
      fill-antialias: true
  - id: landuse_garages
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, garages]
    ]
    paint:
      fill-color: rgb(222, 221, 204)
      fill-antialias: true
  - id: landuse_grass
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, grass]
    ]
    paint:
      fill-color: rgb(207, 237, 165)
      fill-antialias: true
  - id: landuse_greenfield
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, greenfield]
    ]
    paint:
      fill-color: rgb(242, 238, 232)
      fill-antialias: true
  - id: landuse_greenhouse_horticulture
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, greenhouse_horticulture]
    ]
    paint:
      fill-color: rgb(237, 240, 214)
      fill-antialias: true
  - id: landuse_landfill
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, landfill]
    ]
    paint:
      fill-color: rgb(182, 182, 144)
      fill-antialias: true
  - id: landuse_military
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, military]
    ]
    paint:
      fill-color: rgb(242, 228, 221)
      fill-antialias: true
  - id: landuse_plant_nursery
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, plant_nursery]
    ]
    paint:
      fill-color: rgb(174, 223, 162)
      fill-antialias: true
  - id: landuse_quarry
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, quarry]
    ]
    paint:
      fill-color: rgb(195, 194, 194)
      fill-antialias: true
  - id: landuse_railway
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, railway]
    ]
    paint:
      fill-color: rgb(236, 218, 233)
      fill-antialias: true
  - id: landuse_recreation_ground
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, recreation_ground]
    ]
    paint:
      fill-color: rgb(223, 252, 226)
      fill-antialias: true
  - id: landuse_religious
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, religious]
    ]
    paint:
      fill-color: rgb(205, 204, 201)
      fill-antialias: true
  - id: landuse_reservoir
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, reservoir]
    ]
    paint:
      fill-color: rgb(170, 211, 223)
      fill-antialias: true
  - id: landuse_salt_pond
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, salt_pond]
    ]
    paint:
      fill-color: rgb(170, 211, 223)
      fill-antialias: true
  - id: landuse_village_green
    layer: landuse
    type: fill
    layout:
      visibility: visible
    filter: [
      all,
      [==, landuse, village_green]
    ]
    paint:
      fill-color: rgb(205, 235, 176)
      fill-antialias: true