id: water
type: polygon
queries:
  - minZoom: 0
    maxZoom: 14
    sql: |
      SELECT ogc_fid, hstore(''), geometry
      FROM osm_water_polygons
  - minZoom: 0
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_ways_z${zoom} 
      WHERE geometrytype(geom) LIKE '%POLYGON%'
        AND (tags -> 'natural' = 'water' OR tags -> 'waterway' IN ('riverbank', 'dock'))
  - minZoom: 0
    maxZoom: 20
    sql: |
      SELECT id, tags, geom 
      FROM osm_relations_z${zoom} 
      WHERE geometrytype(geom) LIKE '%POLYGON%'
        AND (tags -> 'natural' = 'water' OR tags -> 'waterway' IN ('riverbank', 'dock'))
